"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { FileText, Download, BarChart3, TrendingUp, AlertTriangle } from "lucide-react"

export default function ReportsPage() {
  const handleGenerateReport = (reportType: string) => {
    // Generate sample report data
    const reportData = {
      title: `Heavy Metal Pollution ${reportType} Report`,
      generatedDate: new Date().toISOString(),
      sites: [
        { id: "NYC-001", name: "Central Park Reservoir", hmpi: 85.2, risk: "Medium" },
        { id: "NYC-002", name: "Brooklyn Bridge Area", hmpi: 142.8, risk: "High" },
        { id: "NYC-003", name: "Queens Monitoring Site", hmpi: 67.4, risk: "Low" },
      ],
      summary: {
        totalSites: 15,
        highRiskSites: 4,
        mediumRiskSites: 7,
        lowRiskSites: 4,
        averageHMPI: 89.6,
      },
    }

    // Create and download report
    const reportContent = `Heavy Metal Pollution ${reportType} Report
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
================
Total Monitoring Sites: ${reportData.summary.totalSites}
Average HMPI Score: ${reportData.summary.averageHMPI}
High Risk Sites: ${reportData.summary.highRiskSites}
Medium Risk Sites: ${reportData.summary.mediumRiskSites}
Low Risk Sites: ${reportData.summary.lowRiskSites}

SITE DETAILS
============
${reportData.sites
  .map(
    (site) =>
      `${site.id} - ${site.name}
  HMPI Score: ${site.hmpi}
  Risk Level: ${site.risk}
  `,
  )
  .join("\n")}

RECOMMENDATIONS
===============
1. Immediate attention required for high-risk sites
2. Regular monitoring of medium-risk areas
3. Continued surveillance of low-risk locations
4. Implementation of remediation measures where necessary

Report generated by Heavy Metal Pollution Indices System
`

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `HMPI_${reportType}_Report_${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Reports</h1>
        <p className="text-gray-600 mt-2">Generate comprehensive pollution assessment reports</p>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <FileText className="h-5 w-5 text-blue-600" />
              <div>
                <p className="text-sm text-gray-600">Total Reports</p>
                <p className="text-2xl font-bold">247</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <TrendingUp className="h-5 w-5 text-green-600" />
              <div>
                <p className="text-sm text-gray-600">This Month</p>
                <p className="text-2xl font-bold">18</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <AlertTriangle className="h-5 w-5 text-red-600" />
              <div>
                <p className="text-sm text-gray-600">Critical Reports</p>
                <p className="text-2xl font-bold">5</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <BarChart3 className="h-5 w-5 text-purple-600" />
              <div>
                <p className="text-sm text-gray-600">Avg HMPI</p>
                <p className="text-2xl font-bold">89.6</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Report Generation */}
      <Card>
        <CardHeader>
          <CardTitle>Generate New Report</CardTitle>
          <CardDescription>Create comprehensive pollution assessment reports</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="report-type">Report Type</Label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select report type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="comprehensive">Comprehensive Assessment</SelectItem>
                  <SelectItem value="summary">Executive Summary</SelectItem>
                  <SelectItem value="technical">Technical Analysis</SelectItem>
                  <SelectItem value="compliance">Compliance Report</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="time-period">Time Period</Label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select time period" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="last-week">Last Week</SelectItem>
                  <SelectItem value="last-month">Last Month</SelectItem>
                  <SelectItem value="last-quarter">Last Quarter</SelectItem>
                  <SelectItem value="last-year">Last Year</SelectItem>
                  <SelectItem value="custom">Custom Range</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="start-date">Start Date</Label>
              <Input type="date" id="start-date" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="end-date">End Date</Label>
              <Input type="date" id="end-date" />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="sites">Monitoring Sites</Label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="Select sites to include" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Sites</SelectItem>
                <SelectItem value="high-risk">High Risk Sites Only</SelectItem>
                <SelectItem value="custom">Custom Selection</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <Button onClick={() => handleGenerateReport("Comprehensive")} className="w-full">
            <Download className="h-4 w-4 mr-2" />
            Generate Report
          </Button>
        </CardContent>
      </Card>

      {/* Recent Reports */}
      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
          <CardDescription>Previously generated pollution assessment reports</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {[
              {
                name: "Monthly Comprehensive Report - December 2024",
                date: "2024-12-15",
                type: "Comprehensive",
                status: "Complete",
              },
              { name: "High Risk Sites Analysis", date: "2024-12-10", type: "Technical", status: "Complete" },
              { name: "Quarterly Compliance Report Q4", date: "2024-12-05", type: "Compliance", status: "Complete" },
              { name: "Emergency Assessment - Brooklyn", date: "2024-12-01", type: "Emergency", status: "Critical" },
            ].map((report, index) => (
              <div key={index} className="flex items-center justify-between p-4 border rounded-lg">
                <div className="flex items-center space-x-3">
                  <FileText className="h-5 w-5 text-gray-500" />
                  <div>
                    <p className="font-medium">{report.name}</p>
                    <p className="text-sm text-gray-600">Generated on {report.date}</p>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <Badge variant={report.status === "Critical" ? "destructive" : "secondary"}>{report.type}</Badge>
                  <Button variant="outline" size="sm">
                    <Download className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
